bruteforce

diff --git a/.github/workflows/macos.yml b/.github/workflows/macos.yml
--- a/.github/workflows/macos.yml
+++ b/.github/workflows/macos.yml
@@ -206,9 +206,43 @@ jobs:
 
           lipo -create -output qfield-universal/qfield.app/Contents/MacOS/qfield /Volumes/QField\ Installer/qfield.app/Contents/MacOS/qfield /Volumes/QField\ Installer\ 1/qfield.app/Contents/MacOS/qfield
 
-          sleep 1 # hdiutil: create failed - Resource busy
+          while ! create-dmg \
+              --volname "QField" \
+              --hide-extension qfield.app \
+              --volicon "/Volumes/QField Installer/qfield.app/Contents/Resources/qfield_logo.icns" \
+              --background "/Volumes/QField Installer/.background/installer_background.png" \
+              --window-pos 200 120 \
+              --window-size 512 320 \
+              --icon-size 100 \
+              --icon "qfield.app" 130 160 \
+              --app-drop-link 400 155 \
+              --codesign "Apple Development" \
+              qfield-universal.dmg \
+              qfield-universal/qfield.app || (( count++ >= 10 ));
+          do
+              sleep 1
+              echo "Retry ..."
+          done
 
-          create-dmg --volname "QField" --hide-extension qfield.app --volicon "/Volumes/QField Installer/qfield.app/Contents/Resources/qfield_logo.icns" --background "/Volumes/QField Installer/.background/installer_background.png" --window-pos 200 120 --window-size 512 320 --icon-size 100 --icon "qfield.app" 130 160 --app-drop-link 400 155 --codesign "Apple Development" qfield-universal.dmg qfield-universal/qfield.app
+          echo "!Failed 10 attempts retrying with sudo"
+
+          while ! sudo create-dmg \
+              --volname "QField" \
+              --hide-extension qfield.app \
+              --volicon "/Volumes/QField Installer/qfield.app/Contents/Resources/qfield_logo.icns" \
+              --background "/Volumes/QField Installer/.background/installer_background.png" \
+              --window-pos 200 120 \
+              --window-size 512 320 \
+              --icon-size 100 \
+              --icon "qfield.app" 130 160 \
+              --app-drop-link 400 155 \
+              --codesign "Apple Development" \
+              qfield-universal.dmg \
+              qfield-universal/qfield.app || (( count++ >= 10 ));
+          do
+              sleep 1
+              echo "Retry"
+          done
 
           hdiutil detach /dev/disk2s1
           hdiutil detach /dev/disk3s1
